server:
  port: 8206

spring:
  application:
    name: service-order
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    username: root
    password: 19970815
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://8.140.126.195:27017/yygh_hosp
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: 8.140.126.195
    port: 5672
    username: guest
    password: guest
  redis:
    host: 8.140.126.195
    password: Ljs19970815!
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

#配置mapper.xml文件路径
mybatis-plus:
  mapper-locations: com/ljs/appointment/order/mapper/xml/*.xml

weixin:
  appid: wx74862e0dfcf69954
  partner: 1558950191
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  cert: H:\\java学习\\尚医通\\06-工具软件\\支付退款证书\\cert\\apiclient_cert.p12