server:
  port: 8202

spring:
  application:
    name: service-cmn
  profiles:
    active: dev
  #数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 19970815
  #返回json格式数据
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 169.254.27.128
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        #最大阻塞时间(如负数 则无限制)
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#配置mapper.xml文件路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml